# Generated by Django 6.0.5 on 2026-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.ImageField(upload_to='media')),
                ('lige', models.ImageField(upload_to='media')),
                ('narxi', models.IntegerField(null=True)),
                ('narxi1', models.IntegerField(null=True)),
                ('namc', models.CharField(max_length=200, null=True)),
                ('tavk', models.CharField(max_length=200, null=True)),
                ('namr', models.CharField(max_length=200, null=True)),
                ('tavt', models.CharField(max_length=200, null=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Kik',
        ),
    ]
