# Generated by Django 6.0.5 on 2026-09-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0002_kit_delete_kik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kit',
            new_name='Kik',
        ),
    ]
